services:
  - type: worker
    name: furry-hub-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false